03 정수론
Altu-Bitu-6/Altu-Bitu-KoEunbi pull request #3
Opened 2024-03-05 05:14 UTC by eeeunbiiii

인적사항
학번: 2271069
이름: 고은비

과제제출
기존 제출: 1735, 2840, 6588  
추가 제출:

2024-03-06 15:38 UTC, chae-jpg requested changes
**[정수론 이론 코드리뷰 완료]**

1735(P3), 6588(P1)
은비님 안녕하세요! 코드 리뷰 완료되었습니다👍
6588번 문제에서 현재 오답 판정이 나오고 있습니다 😢 리뷰 확인하시고 수정해주시면 좋을 것 같아요!
궁금하신 점이 있다면 언제나 리뷰어를 호출해주세요😊

2024-03-06 15:38 UTC, chae-jpg commented on 03_정수론/필수/1735.cpp
> +int getGcd(int a, int b) {
유클리드 호제법을 잘 구현해주셨어요!

2024-03-06 15:38 UTC, chae-jpg commented on 03_정수론/필수/1735.cpp
> +    cout << num / gcd << " " << deno / gcd;
기약분수가 되기 위한 조건을 이용해서 새로운 분자와 분모를 잘 찾아주셨네요!

2024-03-06 15:38 UTC, chae-jpg commented on 03_정수론/필수/6588.cpp
> +void findPrime(bool b[], int n) {
에라토스테네스의 체를 이용해서 소수를 잘 판정해주셨네요!

2024-03-06 15:38 UTC, chae-jpg commented on 03_정수론/필수/6588.cpp
> +			}
합이 두 소수로 이루어진 경우를 구해둔 소수 여부 배열을 이용해서 잘 찾아주셨어요!

2024-03-06 15:38 UTC, chae-jpg commented on 03_정수론/필수/6588.cpp
> +	bool prime[1000000] = { 0, };
P3
이 문제의 1000000처럼 자주 쓰이는 큰 숫자는 전역상수로 선언해주는 편이 편리합니다.
```
const int MAX = 1000000
```
처럼요! 1e6으로 선언도 가능합니다~

2024-03-06 15:38 UTC, chae-jpg commented on 03_정수론/필수/6588.cpp
> +int main() {
P1
입출력 과정에서 입력, 출력되는 숫자가 많아서 백준 상으로 시간초과가 나고 있어요 😢 
입출력 속도를 향상시키는 코드를 추가하면 바로 정답이 나올 거에요!

2024-03-08 10:56 UTC, eeeunbiiii commented on 03_정수론/필수/6588.cpp
> +int main() {
@chae-jpg 넵 감사합니다! 해결했습니다 :)

2024-03-10 10:39 UTC, kimhj010502 reviewed
**[정수론 구현 문제 코드 리뷰 완료]**

2840(P2)

은비님 안녕하세요!
과제하시느라 수고 많으셨습니다!! 어려운 문제인데도 잘 풀어주셨네요! 🥰 
코드에 대한 간단한 주석이 있으면 더 좋을 것 같아요. 😎
몇 가지 사소한 코멘트 드렸습니다.
궁금한 점이 있으면 리뷰어를 호출해주세요!

2024-03-10 10:39 UTC, kimhj010502 commented on 03_정수론/필수/2840.cpp
> +int main() {
P2. 모든 연산을 main 함수에서 해주었네요~ 알튜비튜에서는 함수로 구현할 수 있는 부분은 최대한 함수를 따로 정의해서 사용하는 것을 권장하고 있어요!

2024-03-10 10:39 UTC, kimhj010502 commented on 03_정수론/필수/2840.cpp
> +		}
`find` 함수를 사용하여 알파벳의 중복을 체크해주셨네요~ 이 방법도 좋지만 arr의 크기가 커지면 시간 초과가 발생할 수 있으니 알파벳의 중복을 체크하는 vector를 만들어서 관리하는 샘플 답안 코드를 참고해주세요!

2024-03-10 10:39 UTC, kimhj010502 commented on 03_정수론/필수/2840.cpp
> +	while (cnt) {
`while (cnt--)`로 작성해주면 while문 안에 있는 `cnt--;`를 따로 작성할 필요가 없습니다~!

2024-03-10 13:10 UTC, merged